algo = input("Diga algo: ")
print("O tipo primitivo desse valor é {}".format(type(algo)))
print("Só tem espaços? {}".format(algo.isspace()))
print("É um número? {}".format(algo.isnumeric()))
print("É alfabético? {}".format(algo.isalpha()))
print("É alfanúmerico? {}".format(algo.isalnum()))
print("Está em maiúsculas? {}".format(algo.isupper()))
print("Está em minúsculas? {}".format(algo.islower()))
print("Está capitalizado? {}".format(algo.istitle()))